### ISSUE TITLE
CrossOriginで通信できなくなってる(back)(front)

### ISSUE THREAD

**Issue by nozo-moto** [AizuGeekDojo/EnterLeaveSystem#70]
起動スクリプトを使うと通信できなくなるので修正が急務
http://tacamy.hatenablog.com/entry/2016/10/16/182658

**Comment by nozo-moto** [comment]
Jun 11 17:04:18 raspberrypi pipenv[2384]: Traceback (most recent call last):
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.run_application()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.run_websocket()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
Jun 11 17:04:18 raspberrypi pipenv[2384]:     list(self.application(self.environ, lambda s, h, e=None: []))
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2301, in __call__
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return self.wsgi_app(environ, start_response)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2287, in wsgi_app
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.handle_exception(e)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1733, in handle_exception
Jun 11 17:04:18 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:18 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.full_dispatch_request()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return self.finalize_request(rv)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1823, in finalize_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.make_response(rv)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1949, in make_response
Jun 11 17:04:18 raspberrypi pipenv[2384]:     'The view function did not return a valid response. The'
Jun 11 17:04:18 raspberrypi pipenv[2384]: TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Jun 11 17:04:18 raspberrypi pipenv[2384]: Mon Jun 11 17:02:20 2018 {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '60240', 'HTTP_HOST': 'localhost:3000', (hidden keys: 30)} failed with TypeError
Jun 11 17:04:18 raspberrypi pipenv[2384]: Traceback (most recent call last):
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.run_application()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 87, in run_application
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return super(WebSocketHandler, self).run_application()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.result = self.application(self.environ, self.start_response)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2301, in __call__
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return self.wsgi_app(environ, start_response)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2287, in wsgi_app
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.handle_exception(e)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1733, in handle_exception
Jun 11 17:04:18 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:18 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.full_dispatch_request()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1807, in full_dispatch_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     rv = self.handle_user_exception(e)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1710, in handle_user_exception
Jun 11 17:04:18 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:18 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1805, in full_dispatch_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     rv = self.dispatch_request()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "server.py", line 53, in logHandler
Jun 11 17:04:18 raspberrypi pipenv[2384]:     res = addLog(req_json)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/EnterLeaveSystem/back/handler.py", line 77, in addLog
Jun 11 17:04:18 raspberrypi pipenv[2384]:     slack.postData(uname, sid, isent, int(ts/1000), ext)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/EnterLeaveSystem/back/Slack.py", line 19, in postData
Jun 11 17:04:18 raspberrypi pipenv[2384]:     purpose = ext["anke-to1"]
Jun 11 17:04:18 raspberrypi pipenv[2384]: TypeError: string indices must be integers
Jun 11 17:04:18 raspberrypi pipenv[2384]: Mon Jun 11 17:03:11 2018 {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '60450', 'HTTP_HOST': 'localhost:3000', (hidden keys: 26)} failed with TypeError
Jun 11 17:04:18 raspberrypi pipenv[2384]: Traceback (most recent call last):
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.run_application()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.run_websocket()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
Jun 11 17:04:18 raspberrypi pipenv[2384]:     list(self.application(self.environ, lambda s, h, e=None: []))
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2301, in __call__
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return self.wsgi_app(environ, start_response)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2287, in wsgi_app
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.handle_exception(e)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1733, in handle_exception
Jun 11 17:04:18 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:18 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.full_dispatch_request()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return self.finalize_request(rv)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1823, in finalize_request
Jun 11 17:04:18 raspberrypi pipenv[2384]:     response = self.make_response(rv)
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1949, in make_response
Jun 11 17:04:18 raspberrypi pipenv[2384]:     'The view function did not return a valid response. The'
Jun 11 17:04:18 raspberrypi pipenv[2384]: TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Jun 11 17:04:18 raspberrypi pipenv[2384]: Mon Jun 11 17:04:18 2018 {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '60884', 'HTTP_HOST': 'localhost:3000', (hidden keys: 30)} failed with TypeError
Jun 11 17:04:18 raspberrypi pipenv[2384]: Traceback (most recent call last):
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
Jun 11 17:04:18 raspberrypi pipenv[2384]:     self.run_application()
Jun 11 17:04:18 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 87, in run_application
Jun 11 17:04:18 raspberrypi pipenv[2384]:     return super(WebSocketHandler, self).run_application()
Jun 11 17:04:20 raspberrypi kernel: [ 1360.332821] Under-voltage detected! (0x00050005)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
Jun 11 17:04:24 raspberrypi pipenv[2384]:     self.result = self.application(self.environ, self.start_response)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2301, in __call__
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return self.wsgi_app(environ, start_response)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2287, in wsgi_app
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.handle_exception(e)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1733, in handle_exception
Jun 11 17:04:24 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:24 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.full_dispatch_request()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1807, in full_dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     rv = self.handle_user_exception(e)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1710, in handle_user_exception
Jun 11 17:04:24 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:24 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1805, in full_dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     rv = self.dispatch_request()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "server.py", line 53, in logHandler
Jun 11 17:04:24 raspberrypi pipenv[2384]:     res = addLog(req_json)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/EnterLeaveSystem/back/handler.py", line 77, in addLog
Jun 11 17:04:24 raspberrypi pipenv[2384]:     slack.postData(uname, sid, isent, int(ts/1000), ext)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/EnterLeaveSystem/back/Slack.py", line 19, in postData
Jun 11 17:04:24 raspberrypi pipenv[2384]:     purpose = ext["anke-to1"]
Jun 11 17:04:24 raspberrypi pipenv[2384]: TypeError: string indices must be integers
Jun 11 17:04:24 raspberrypi pipenv[2384]: Mon Jun 11 17:04:18 2018 {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '33158', 'HTTP_HOST': 'localhost:3000', (hidden keys: 26)} failed with TypeError
Jun 11 17:04:24 raspberrypi pipenv[2384]: Traceback (most recent call last):
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
Jun 11 17:04:24 raspberrypi pipenv[2384]:     self.run_application()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 75, in run_application
Jun 11 17:04:24 raspberrypi pipenv[2384]:     self.run_websocket()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
Jun 11 17:04:24 raspberrypi pipenv[2384]:     list(self.application(self.environ, lambda s, h, e=None: []))
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2301, in __call__
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return self.wsgi_app(environ, start_response)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2287, in wsgi_app
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.handle_exception(e)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1733, in handle_exception
Jun 11 17:04:24 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:24 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.full_dispatch_request()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return self.finalize_request(rv)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1823, in finalize_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.make_response(rv)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1949, in make_response
Jun 11 17:04:24 raspberrypi pipenv[2384]:     'The view function did not return a valid response. The'
Jun 11 17:04:24 raspberrypi pipenv[2384]: TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Jun 11 17:04:24 raspberrypi pipenv[2384]: Mon Jun 11 17:04:24 2018 {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '33200', 'HTTP_HOST': 'localhost:3000', (hidden keys: 30)} failed with TypeError
Jun 11 17:04:24 raspberrypi pipenv[2384]: Traceback (most recent call last):
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
Jun 11 17:04:24 raspberrypi pipenv[2384]:     self.run_application()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/geventwebsocket/handler.py", line 87, in run_application
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return super(WebSocketHandler, self).run_application()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
Jun 11 17:04:24 raspberrypi pipenv[2384]:     self.result = self.application(self.environ, self.start_response)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2301, in __call__
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return self.wsgi_app(environ, start_response)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2287, in wsgi_app
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.handle_exception(e)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1733, in handle_exception
Jun 11 17:04:24 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:24 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
Jun 11 17:04:24 raspberrypi pipenv[2384]:     response = self.full_dispatch_request()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1807, in full_dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     rv = self.handle_user_exception(e)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1710, in handle_user_exception
Jun 11 17:04:24 raspberrypi pipenv[2384]:     reraise(exc_type, exc_value, tb)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jun 11 17:04:24 raspberrypi pipenv[2384]:     raise value
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1805, in full_dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     rv = self.dispatch_request()
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/.local/share/virtualenvs/back-NC72SwVh/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
Jun 11 17:04:24 raspberrypi pipenv[2384]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "server.py", line 53, in logHandler
Jun 11 17:04:24 raspberrypi pipenv[2384]:     res = addLog(req_json)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/EnterLeaveSystem/back/handler.py", line 77, in addLog
Jun 11 17:04:24 raspberrypi pipenv[2384]:     slack.postData(uname, sid, isent, int(ts/1000), ext)
Jun 11 17:04:24 raspberrypi pipenv[2384]:   File "/home/pi/EnterLeaveSystem/back/Slack.py", line 19, in postData
Jun 11 17:04:24 raspberrypi pipenv[2384]:     purpose = ext["anke-to1"]
Jun 11 17:04:24 raspberrypi pipenv[2384]: TypeError: string indices must be integers
Jun 11 17:04:24 raspberrypi pipenv[2384]: Mon Jun 11 17:04:24 2018 {'REMOTE_ADDR': '::1', 'REMOTE_PORT': '33218', 'HTTP_HOST': 'localhost:3000', (hidden keys: 26)} failed with TypeError
Jun 11 17:04:36 raspberrypi kernel: [ 1376.972904] Voltage normalised (0x00000000)
Jun 11 17:04:38 raspberrypi kernel: [ 1379.052860] Under-voltage detected! (0x00050005)

**Comment by nozo-moto** [comment]
解決ed
